name = "ClimateMARGO"
uuid = "d3f62095-a717-45bf-aadc-ac9dfc258fa6"
repo = "https://github.com/ClimateMARGO/ClimateMARGO.jl"
version = "0.3.1"

[deps]
CompilerSupportLibraries_jll = "e66e0078-7015-5450-92f7-15fbd957f2ae"
DiffResults = "163ba53b-c6d8-5494-b064-1a9d43ac40c5"
DiffRules = "b552c78f-8df3-52c6-915a-8e097449b14b"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
Ipopt = "b6b21f68-93f8-5de0-b562-5493be1d77c9"
Ipopt_jll = "9cc047cb-c261-5740-88fc-0cf96f7bdcc7"
JSON2 = "2535ab7d-5cd8-5a07-80ac-9b1792aadce3"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
PyPlot = "d330b81b-6aea-500a-939a-2ce795aea3ee"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"

[compat]
DiffResults = "= 1.0.2"
DiffRules = "= 1.0.1"
ForwardDiff = "= 0.10.12"
Ipopt = "= 0.6.5"
JSON2 = "0.3.2"
JuMP = "= 0.21.5"
PyPlot = "2.9.0"
julia = "^1.5"

[extras]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["BenchmarkTools", "Test"]
